name: Log data to google sheet

on:
  push:
    branches: master

  schedule:
    - cron: "0 7 * * *" # 12.30am IST

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Fetch data from wakatime & log to google sheet
        run: node ./index.js
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.WAKATIME_API_KEY }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
